documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

ci:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

source:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.js"
          - "**/*.ts"
          - "**/*.py"
          - "**/*.go"
          - "**/*.java"
